var res = {
    s_Arial_fnt : "res/Art/Arial.fnt",
    s_Arial_png : "res/Art/Arial.png",
    s_achievement_50 : "res/Art/achievement_50.png",
    s_addbomb : "res/Art/addbomb.png",
    s_bg : "res/Art/bg.jpg",
    s_bomb : "res/Art/bomb.png",
    s_bomb40 : "res/Art/bomb40.png",
    s_bomb64 : "res/Art/bomb64.png",
    s_bomb_icon : "res/Art/bomb_icon.png",
    s_brag_button : "res/Art/brag_button.png",
    s_button_brag : "res/Art/button_brag.png",
    s_button_brag_hot : "res/Art/button_brag_hot.png",
    s_button_challenge : "res/Art/button_challenge.png",
    s_button_challenge_hot : "res/Art/button_challenge_hot.png",
    s_button_mainmenu : "res/Art/button_mainmenu.png",
    s_button_play : "res/Art/button_play.png",
    s_button_play_hot : "res/Art/button_play_hot.png",
    s_button_scoreboardchallenge : "res/Art/button_scoreboardchallenge.png",
    s_button_scores : "res/Art/button_scores.png",
    s_button_small : "res/Art/button_small.png",
    s_button_store : "res/Art/button_store.png",
    s_button_store_hot : "res/Art/button_store_hot.png",
    s_challenge_button : "res/Art/challenge_button.png",
    s_close_button : "res/Art/close_button.png",
    s_coin40 : "res/Art/coin40.png",
    s_coin64 : "res/Art/coin64.png",
    s_coin_600 : "res/Art/coin_600.png",
    s_coin_bundle64 : "res/Art/coin_bundle64.png",
    s_coin_bundle_icon : "res/Art/coin_bundle_icon.png",
    s_coin_icon : "res/Art/coin_icon.png",
    s_cross_red : "res/Art/cross_red.png",
    s_frontscreen_background : "res/Art/frontscreen_background.png",
    s_heart : "res/Art/heart.png",
    s_heart40 : "res/Art/heart40.png",
    s_heart64 : "res/Art/heart64.png",
    s_heart_icon : "res/Art/heart_icon.png",
    s_heart_red : "res/Art/heart_red.png",
    s_isloading : "res/Art/isloading.png",
    s_loading_1 : "res/Art/loading_1.png",
    s_loading_2 : "res/Art/loading_2.png",
    s_loading_3 : "res/Art/loading_3.png",
    s_loading_4 : "res/Art/loading_4.png",
    s_loading_5 : "res/Art/loading_5.png",
    s_loading_6 : "res/Art/loading_6.png",
    s_loading_7 : "res/Art/loading_7.png",
    s_loading_8 : "res/Art/loading_8.png",
    s_loadingspinner : "res/Art/loadingspinner.png",
    s_login_button : "res/Art/login_button.png",
    s_logo_jpg : "res/Art/logo.jpg",
    s_logo_png : "res/Art/logo.png",
    s_logo64 : "res/Art/logo64.png",
    s_logo_large : "res/Art/logo_large.jpg",
    s_logout_button : "res/Art/logout_button.png",
    s_mainmenu_button : "res/Art/mainmenu_button.png",
    s_mobile64 : "res/Art/mobile64.png",
    s_mobile_icon : "res/Art/mobile_icon.png",
    s_modal_box : "res/Art/modal_box.png",
    s_modal_box_copy2 : "res/Art/modal_box_copy2.png",
    s_nonfriend_1 : "res/Art/nonfriend_1.png",
    s_nonfriend_10 : "res/Art/nonfriend_10.png",
    s_nonfriend_2 : "res/Art/nonfriend_2.png",
    s_nonfriend_3 : "res/Art/nonfriend_3.png",
    s_nonfriend_4 : "res/Art/nonfriend_4.png",
    s_nonfriend_5 : "res/Art/nonfriend_5.png",
    s_nonfriend_6 : "res/Art/nonfriend_6.png",
    s_nonfriend_7 : "res/Art/nonfriend_7.png",
    s_nonfriend_8 : "res/Art/nonfriend_8.png",
    s_nonfriend_9 : "res/Art/nonfriend_9.png",
    s_pack_600 : "res/Art/pack_600.png",
    s_pagebg : "res/Art/pagebg.jpg",
    s_panel_welcome : "res/Art/panel_welcome.png",
    s_playnow_button : "res/Art/playnow_button.png",
    s_plus_1 : "res/Art/plus_1.png",
    s_plus_2 : "res/Art/plus_2.png",
    s_plus_3 : "res/Art/plus_3.png",
    s_scoreboardentry_right : "res/Art/scoreboardentry_right.png",
    s_scoreboardentry_tournament : "res/Art/scoreboardentry_tournament.png",
    s_scores64 : "res/Art/scores64.png",
    s_scores_button : "res/Art/scores_button.png",
    s_scorestub_even : "res/Art/scorestub_even.png",
    s_scorestub_odd : "res/Art/scorestub_odd.png",
    s_sparkleoutterparticle : "res/Art/sparkleoutterparticle.png",
    s_sparkleparticle : "res/Art/sparkleparticle.png",
    s_store64 : "res/Art/store64.png",
    s_topbar_repeater : "res/Art/topbar_repeater.jpg",
    s_welcome_panel : "res/Art/welcome_panel.png",
    s_login0 : "res/login0.png",
    s_login1 : "res/login1.png",
    s_logout0 : "res/logout0.png",
    s_logout1 : "res/logout1.png"
}

var g_resources = [
    //image
    res.s_Arial_fnt,
    res.s_Arial_png,
    res.s_achievement_50,
    res.s_addbomb,
    res.s_bg,
    res.s_bomb,
    res.s_bomb40,
    res.s_bomb64,
    res.s_bomb_icon,
    res.s_brag_button,
    res.s_button_brag,
    res.s_button_brag_hot,
    res.s_button_challenge,
    res.s_button_challenge_hot,
    res.s_button_mainmenu,
    res.s_button_play,
    res.s_button_play_hot,
    res.s_button_scoreboardchallenge,
    res.s_button_scores,
    res.s_button_small,
    res.s_button_store,
    res.s_button_store_hot,
    res.s_challenge_button,
    res.s_close_button,
    res.s_coin40,
    res.s_coin64,
    res.s_coin_600,
    res.s_coin_bundle64,
    res.s_coin_bundle_icon,
    res.s_coin_icon,
    res.s_cross_red,
    res.s_frontscreen_background,
    res.s_heart,
    res.s_heart40,
    res.s_heart64,
    res.s_heart_icon,
    res.s_heart_red,
    res.s_isloading,
    res.s_loading_1,
    res.s_loading_2,
    res.s_loading_3,
    res.s_loading_4,
    res.s_loading_5,
    res.s_loading_6,
    res.s_loading_7,
    res.s_loading_8,
    res.s_loadingspinner,
    res.s_login_button,
    res.s_logo_jpg,
    res.s_logo_png,
    res.s_logo64,
    res.s_logo_large,
    res.s_logout_button,
    res.s_mainmenu_button,
    res.s_mobile64,
    res.s_mobile_icon,
    res.s_modal_box,
    res.s_modal_box_copy2,
    res.s_nonfriend_1,
    res.s_nonfriend_10,
    res.s_nonfriend_2,
    res.s_nonfriend_3,
    res.s_nonfriend_4,
    res.s_nonfriend_5,
    res.s_nonfriend_6,
    res.s_nonfriend_7,
    res.s_nonfriend_8,
    res.s_nonfriend_9,
    res.s_pack_600,
    res.s_pagebg,
    res.s_panel_welcome,
    res.s_playnow_button,
    res.s_plus_1,
    res.s_plus_2,
    res.s_plus_3,
    res.s_scoreboardentry_right,
    res.s_scoreboardentry_tournament,
    res.s_scores64,
    res.s_scores_button,
    res.s_scorestub_even,
    res.s_scorestub_odd,
    res.s_sparkleoutterparticle,
    res.s_sparkleparticle,
    res.s_store64,
    res.s_topbar_repeater,
    res.s_welcome_panel,
    res.s_login0,
    res.s_login1,
    res.s_logout0,
    res.s_logout1,
    //plist

    //fnt
    res.s_Arial_png,
    res.s_Arial_fnt

    //tmx

    //bgm

    //effect
];